/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/PermissionJudgment" |
       "/pages/coach/coachHome" |
       "/pages/learnDrive/index" |
       "/pages/login/index" |
       "/pages/login/privacy" |
       "/pages/login/RealNameAuthen" |
       "/pages/login/termsUse" |
       "/pages/student/StudentHome" |
       "/pages/learnDrive/driveSchoolDetail/driveSchoolDetail" |
       "/pages/learnDrive/onlineSignUp/onlineSignUp" |
       "/pages/learnDrive/physicalExamination/hospitalDetail" |
       "/pages/learnDrive/physicalExamination/hospitalList" |
       "/pages/learnDrive/serviceEvaluation/serviceEvaluation" |
       "/pages/learnDrive/volumeUp/volumeUp" |
       "/pages/learnDrive/driveSchoolDetail/component/carType" |
       "/pages/learnDrive/driveSchoolDetail/component/Coach" |
       "/pages/learnDrive/driveSchoolDetail/component/Comment" |
       "/pages/learnDrive/driveSchoolDetail/component/introduce" |
       "/pages/learnDrive/driveSchoolDetail/component/site" |
       "/devTools/page/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
